//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop228.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class buying
    {
        public int id { get; set; }
        public string customerFname { get; set; }
        public string customerLname { get; set; }
        public int carID { get; set; }
        public string purchaseAmount { get; set; }
        public System.DateTime purchaseDate { get; set; }
    
        public virtual car car { get; set; }
    }
}
